language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
  sudo apt-get update;
  sudo apt-get install libgflags-dev
#install:
script: ./build.sh && ./build/release/eugenics/eugenics