language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install: sudo apt-get update
install: sudo apt-get install libgflags-dev
script: ./build.sh && ./build/release/eugenics/eugenics