language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
  sudo apt-get update -qq
  sudo apt-get install -qq libgflags-dev
#install:
script: ./build.sh && ./build/release/eugenics/eugenics