notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5bf3083a903021096f00
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: false     # default: false
language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
  - git reset --hard HEAD
  - git clean -fdx
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install -y build-essential
  - sudo pip install cpp-coveralls
  # - wget --quiet http://ftp.ussg.iu.edu/linux/ubuntu/pool/main/g/gflags/libgflags2_2.0-1.1ubuntu1_i386.deb
  # - wget --quiet http://ftp.ussg.iu.edu/linux/ubuntu/pool/main/g/gflags/libgflags-dev_2.0-1.1ubuntu1_i386.deb
  # - sudo dpkg -i libgflags2_2.0-1.1ubuntu1_i386.deb
  # - sudo dpkg -i libgflags-dev_2.0-1.1ubuntu1_i386.deb
#  sudo apt-get install libgflags-dev
install:
  - cd eugenics-system
  - ./share/scripts/install-gflags.sh
  - cd ..
script:
  - rm -rf build debug
  - ./build.sh && ./build/eugenics/eugenics